### ISSUE TITLE
How do you compile this library?

### ISSUE THREAD

**Issue by lukovdm** [Airblader/xcb-util-xrm#67] opened 2016-07-23 17:58 UTC
I can't figure out how to compile this.

I have tried: `autoreconf --install`

```
configure.ac:16: error: must install xorg-macros 1.16.0 or later before running autoconf/autogen
m4/xcb_util_common.m4:8: XCB_UTIL_COMMON is expanded from...
configure.ac:16: the top level
autom4te: /usr/bin/m4 failed with exit status: 1
aclocal: error: echo failed with exit status: 1
autoreconf: aclocal failed with exit status: 1
```

but it doesn't work.

Any ideas?

**Comment by Airblader** [comment] 2016-07-23 18:02
Ideally you don't compile it at all. Please ask your distro maintainers to provide a proper package. 

If you must compile from source, I suggest looking at the package build instructions for other xcb util libraries on your platform and adapt them accordingly. For example, refer to xcb-util-cursor.

**Comment by Airblader** [comment] 2016-07-23 18:03
(The error message is pretty clear though. You need to install xorg-macros first)

**Comment by Airblader** [comment] 2016-07-23 18:03
I'm closing this as it's not a bug. Feel free to continue commenting.

**Closed by Airblader** 2016-07-23 18:03 UTC

**Comment by psychon** [comment] 2016-07-24 12:05
Just to mention a package name: Debian has the xorg-macros in package xutils-dev.

**Comment by JezerM** [comment] 2021-03-30 03:12
Add: `libtool` package is required.
